Adds Annotatable XBlock extracting from edx-platform repo
openedx/xblocks-contrib pull request #5
Opened 2024-07-24 10:58 UTC by irtazaakram

2024-07-24 12:18 UTC, farhan requested changes

2024-07-24 12:18 UTC, farhan commented on xblocks_contrib/annotatable/static/css/annotatable_editor.css
> +/* line 564, /openedx/edx-platform/cms/static/sass/elements/_xblocks.scss */
remove all these comment lines

2024-07-24 12:18 UTC, farhan commented on xblocks_contrib/annotatable/static/css/annotatable.css
> +/* line 1, /openedx/edx-platform/xmodule/assets/AnnotatableBlockDisplay.scss */
Remove all these comment lines

2024-07-24 12:18 UTC, farhan commented on xblocks_contrib/annotatable/translation
> +/Users/irtaza.akram/openedx/edx-platform/src/xblocks-contrib/xblocks-contrib copy/xblocks-contrib/conf/locale
Local machine path should not be commited

2025-03-03 05:01 UTC, irtazaakram commented on xblocks_contrib/annotatable/static/js/src/annotatable.js
> +        annotationsHidden = !annotationsHidden;
This approach doesn't update annotationsHidden, so the change only affects the function temporarily and doesn't persist.

2025-03-03 05:05 UTC, irtazaakram commented on xblocks_contrib/annotatable/static/js/src/annotatable.js
> +        $.extend(position, {
returning a value isn’t needed here since the function just updates the UI.

2025-03-03 05:06 UTC, irtazaakram commented on xblocks_contrib/annotatable/static/js/src/annotatable.js
> +        var hide = instructionsHidden;
https://github.com/openedx/xblocks-contrib/pull/5#discussion_r1976881086

2025-03-05 12:44 UTC, farhan requested changes

2025-03-18 09:22 UTC, irtazaakram commented on xblocks_contrib/annotatable/annotatable.py
> +        self._extract_instructions(xmltree)
This is related to https://github.com/openedx/xblocks-contrib/pull/5#discussion_r1959619009 it is to remove instructions to repeat.

2025-03-18 09:22 UTC, irtazaakram commented on xblocks_contrib/annotatable/static/js/src/annotatable.js
> +        annotationsHidden = !annotationsHidden;
Assigning multiple variables in a single statement like this isn't compliant with ESLint's [no-multi-assign](https://eslint.org/docs/latest/rules/no-multi-assign) rule.

2025-03-20 06:57 UTC, farhan commented
@irtazaakram PR looks good now. Just make sure to:

Test and verify all the tasks mentioned in the PR description.
Fix the corresponding issue in the edx-platform as well.

2025-04-03 10:25 UTC, farhan approved these changes
Good work ⭐

2025-04-14 06:29 UTC, merged